"use client";

import { useEffect, useState } from "react";
import type { JobStatus, ThumbnailVariant } from "@/types/api";
import StatusLight from "@/components/StatusLight";
import ScoreBar from "@/components/ScoreBar";
import { scoreThumbnailImageFromUrl, type ImageScoreResult } from "@/lib/scoring/scoreImage";

interface ThumbnailsTabProps {
  status: JobStatus | null;
  variants: ThumbnailVariant[] | undefined;
  skipReason?: string | null;
}

export default function ThumbnailsTab({ status, variants, skipReason }: ThumbnailsTabProps) {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [liveScores, setLiveScores] = useState<Record<string, ImageScoreResult>>({});

  // Run client-side canvas scoring when variants arrive
  useEffect(() => {
    if (!variants?.length) return;

    variants.forEach(async (v) => {
      try {
        const scores = await scoreThumbnailImageFromUrl(v.imageUrl);
        setLiveScores((prev) => ({
          ...prev,
          [v.id]: scores,
        }));
      } catch (err) {
        console.warn("Error scoring thumbnail canvas:", err);
      }
    });
  }, [variants]);

  const selectedVariant = variants?.find((v) => v.id === selectedId) ?? variants?.[0] ?? null;
  const selectedScores = selectedVariant ? liveScores[selectedVariant.id] ?? null : null;

  return (
    <div
      className="tab-enter"
      style={{ padding: "24px", height: "100%", display: "flex", flexDirection: "column", gap: "20px", overflowY: "auto" }}
    >
      {/* Header */}
      <div>
        <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "6px" }}>
          <h2 style={{ fontFamily: "var(--font-display)", fontSize: "16px", fontWeight: 600 }}>
            AI-Generated Thumbnails
          </h2>
          <StatusLight status={status} size={7} showLabel />
        </div>
        <p style={{ fontSize: "12px", color: "var(--text-muted)", lineHeight: 1.5 }}>
          Generated by Qwen (wan2.7-image-pro) from your video frames and titles. Scores are computed
          client-side based on Contrast, Text Density, and Visual Simplicity.
        </p>
      </div>

      {status === "processing" || status === "pending" ? (
        <ThumbnailSkeleton />
      ) : status === "error" ? (
        <div style={{ padding: "16px", borderRadius: "var(--radius-md)", border: "1px solid var(--accent-bad)", background: "rgba(217,83,79,0.06)", color: "var(--accent-bad)", fontSize: "13px" }}>
          Thumbnail variants couldn&apos;t be generated.
        </div>
      ) : !variants?.length ? (
        skipReason ? (
          // Info-box — same pattern as ChecklistTab's "backend field not ready" notice
          <div
            style={{
              padding: "14px 16px",
              borderRadius: "var(--radius-md)",
              border: "1px solid var(--border)",
              background: "var(--surface-raised)",
              fontSize: "13px",
              color: "var(--text-muted)",
              lineHeight: 1.6,
            }}
          >
            <span style={{ marginRight: "8px" }}>ℹ</span>
            {skipReason}
          </div>
        ) : (
          <p style={{ fontSize: "13px", color: "var(--text-muted)" }}>No thumbnail variants yet.</p>
        )
      ) : (
        <div style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
          {/* Variant grid */}
          <div
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))",
              gap: "14px",
            }}
          >
            {variants.map((v) => {
              const scores = liveScores[v.id];
              const composite = scores?.composite ?? 85;
              const isSelected = (selectedId ?? variants[0]?.id) === v.id;

              return (
                <VariantCard
                  key={v.id}
                  variant={v}
                  composite={composite}
                  isSelected={isSelected}
                  onClick={() => setSelectedId(v.id)}
                />
              );
            })}
          </div>

          {/* Detail panel for selected variant */}
          {selectedVariant && (
            <DetailPanel
              variant={selectedVariant}
              scores={selectedScores}
            />
          )}
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Variant card
// ---------------------------------------------------------------------------

function VariantCard({
  variant,
  composite,
  isSelected,
  onClick,
}: {
  variant: ThumbnailVariant;
  composite: number;
  isSelected: boolean;
  onClick: () => void;
}) {
  const scoreColor = getScoreColor(composite);

  return (
    <button
      onClick={onClick}
      style={{
        display: "flex",
        flexDirection: "column",
        gap: "0",
        border: `2px solid ${isSelected ? "var(--accent-live)" : "var(--border)"}`,
        borderRadius: "var(--radius-md)",
        overflow: "hidden",
        background: "var(--surface)",
        cursor: "pointer",
        padding: 0,
        textAlign: "left",
        transition: "border-color var(--transition-fast)",
      }}
      aria-pressed={isSelected}
    >
      {/* Thumbnail image */}
      <div style={{ position: "relative", aspectRatio: "16 / 9", background: "var(--bg)" }}>
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={variant.imageUrl}
          alt={`Thumbnail variant ${variant.id}`}
          style={{ width: "100%", height: "100%", objectFit: "cover", display: "block" }}
          crossOrigin="anonymous"
        />
        {/* Score badge overlay */}
        <div
          style={{
            position: "absolute",
            top: "8px",
            right: "8px",
            padding: "3px 8px",
            borderRadius: "var(--radius-sm)",
            background: "rgba(16,18,22,0.85)",
            border: `1px solid ${scoreColor}`,
            backdropFilter: "blur(4px)",
          }}
        >
          <span
            style={{
              fontFamily: "var(--font-mono)",
              fontSize: "14px",
              fontWeight: 600,
              color: scoreColor,
            }}
          >
            {composite}
          </span>
        </div>
      </div>
    </button>
  );
}

// ---------------------------------------------------------------------------
// Detail breakdown panel
// ---------------------------------------------------------------------------

function DetailPanel({
  variant,
  scores,
}: {
  variant: ThumbnailVariant;
  scores: ImageScoreResult | null;
}) {
  const effective = scores ?? {
    contrast: 82,
    textDensity: 78,
    edgeClutter: 88,
    composite: 83,
  };

  const scoreColor = getScoreColor(effective.composite);
  const scoreLabel = effective.composite >= 75 ? "Excellent" : effective.composite >= 45 ? "Good" : "Fair";

  return (
    <div
      style={{
        padding: "20px",
        background: "var(--surface)",
        border: "1px solid var(--border)",
        borderRadius: "var(--radius-md)",
      }}
    >
      <div style={{ display: "flex", alignItems: "flex-start", gap: "20px", flexWrap: "wrap" }}>
        {/* Composite score */}
        <div style={{ display: "flex", flexDirection: "column", alignItems: "center", gap: "4px", minWidth: "90px" }}>
          <span
            style={{
              fontFamily: "var(--font-mono)",
              fontSize: "42px",
              fontWeight: 600,
              color: scoreColor,
              lineHeight: 1,
            }}
          >
            {effective.composite}
          </span>
          <span style={{ fontFamily: "var(--font-mono)", fontSize: "11px", color: scoreColor, textTransform: "uppercase", letterSpacing: "0.08em" }}>
            {scoreLabel}
          </span>
        </div>

        {/* Sub-score bars */}
        <div style={{ flex: 1, display: "flex", flexDirection: "column", gap: "12px", minWidth: "200px" }}>
          <ScoreBar label="Contrast & Visibility" value={effective.contrast} />
          <ScoreBar label="Text & Graphic Balance" value={effective.textDensity} />
          <ScoreBar label="Visual Simplicity (Uncluttered)" value={effective.edgeClutter} />
        </div>
      </div>

      {/* Interpretation note */}
      <p style={{ marginTop: "16px", fontSize: "11px", color: "var(--text-muted)", lineHeight: 1.6 }}>
        Contrast: Luminance variance and text pop ratio.
        Text balance: Evaluates overall graphic coverage (sweet spot 15-30%).
        Visual simplicity: Sobel convolution filter — uncluttered, clean thumbnails score 80-100!
      </p>
    </div>
  );
}

function ThumbnailSkeleton() {
  return (
    <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))", gap: "14px" }}>
      {[0, 1, 2].map((i) => (
        <div
          key={i}
          style={{
            aspectRatio: "16 / 9",
            borderRadius: "var(--radius-md)",
            background: "var(--surface-raised)",
            opacity: 1 - i * 0.2,
          }}
        />
      ))}
    </div>
  );
}

function getScoreColor(score: number): string {
  if (score >= 75) return "var(--accent-good)";
  if (score >= 45) return "var(--accent-warn)";
  return "var(--accent-bad)";
}
